### ISSUE TITLE
Counting U bases as well as A, T, C, G

### ISSUE THREAD

**Issue by bdessailly** [wdecoster/nanoQC#10]
![nanoqc_capture](https://user-images.githubusercontent.com/5390068/51996334-cc313180-24b4-11e9-8cc8-5e753080d5e6.PNG)
The frequency of nucleotide plots currently ignore U bases. So when the input Fastq contain RNA sequences, one of the lines is flat (see attached plot). Might be useful to make nanoQC able to handle 'U' bases when relevant.

**Comment by wdecoster** [comment]
Ah yes, great idea. I'll take a look at implementing that.

**Comment by wdecoster** [comment]
In v0.9.0 (available on PyPI) nanoQC will plot 'U' nucleotides if you specify `--rna` when executing the script. Without --rna only A,T,G and C are expected.

Let me know if you have more ideas, and if you want to contribute code then you are more than welcome too!
