### ISSUE TITLE
NanoQC to read bz2 Fastq files as well as gz

### ISSUE THREAD

**Issue by bdessailly** [wdecoster/nanoQC#11]
It would be great for NanoQC to be able to read bz2 files, for coherence with other Nanopack utilities.

**Comment by wdecoster** [comment]
Thanks for the suggestion, I will add this tomorrow.

**Comment by wdecoster** [comment]
In v0.9.0 (available on PyPI) nanoQC reads .gz, .bz2 and uncompressed fastq files. No changes are necessary to your commands - it checks the file extension.

Let me know if you have more ideas, and if you want to contribute code then you are more than welcome too!

**Comment by bdessailly** [comment]
Thanks Wouter!
