### ISSUE TITLE
an TypeError when use nanoQC -l 500

### ISSUE THREAD

**Issue by Biolixue** [wdecoster/nanoQC#12]
Hi Dr.
 I got an error when use nanoQC, the command is :$nanoQC --minlen 100 -o statreports input.fastq.gz
 and error is :
Traceback (most recent call last):
  File "/software/canda/anaconda2/envs/python36/bin/nanoQC", line 11, in <module>
    load_entry_point('nanoQC==0.9.1', 'console_scripts', 'nanoQC')()
  File "/software/canda/anaconda2/envs/python36/lib/python3.6/site-packages/nanoQC-0.9.1-py3.6.egg/nanoQC/nanoQC.py", line 19, in main
TypeError: unsupported operand type(s) for /: 'str' and 'int'

Hope get help from you.
best withes to you

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting this. I have moved this issue to the repository of nanoQC itself.
I have identified the issue and fixed it in version 0.9.2, now available on PyPI/pip.

Let me know if there is anything else I can help you with.

Cheers,
Wouter

**Comment by Biolixue** [comment]
Hi , Dr. Wouter
   Cheers! Now it's working well, Thank you very much.
Best 
Xue

**Comment by wdecoster** [comment]
Good to hear!
