### ISSUE TITLE
BokehDeprecationWarnings with Bokeh v 2.02

### ISSUE THREAD

**Issue by unique379r** [wdecoster/nanoQC#13]
Hi
I am using nanoQC ( https://github.com/wdecoster/nanoQC) which uses Bokeh to plot the analysis of long-read reads but while using I am getting errors "BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead".
Any possible solution or update on it?
Someone from the previous version has reported (PatrikHlobil/Pandas-Bokeh#51) and it seems you have fixed it but this is actually not the case of latest release.

Please have a look.
Thanks

**Comment by wdecoster** [comment]
Thanks for reporting this. Those are not errors, but warnings, NanoQC should just work, even when raising warnings. It would be good to fix these warnings of course, and I'll have a look after my holidays. 

> Someone from the previous version has reported (PatrikHlobil/Pandas-Bokeh#51) and it seems you have fixed it but this is actually not the case of latest release.

NanoQC is unrelated to PatrikHlobil/Pandas-Bokeh.

> Please have a look.

I would suggest "Could you please have a look?" as you are not the one who decides what's on my to-do list. Thanks

**Comment by wdecoster** [comment]
The necessary changes have been made in nanoQC v0.9.4.
