### ISSUE TITLE
TypeError: gridplot() got an unexpected keyword argument 'plot_width'

### ISSUE THREAD

**Issue by sogriffin98** [wdecoster/nanoQC#16]
Hello,

I used the following line of code: 
nanoQC TET_P6.fastq.gz -o /data/ssd2/sgriffin/hornets/Hybrid_Hornets/

I got the following error:
Traceback (most recent call last):
  File "/home/sgriffin/miniconda3/envs/nanoqc/bin/nanoQC", line 10, in <module>
    sys.exit(main())
  File "/home/sgriffin/miniconda3/envs/nanoqc/lib/python3.10/site-packages/nanoQC/nanoQC.py", line 43, in main
    save(gridplot(children=[[hist], seq_plots, qual_plots],
TypeError: gridplot() got an unexpected keyword argument 'plot_width'

Do you know what I could be doing wrong?

Thank you :)

**Comment by wdecoster** [comment]
which version of nanoQC are you using? Could you try updating if it is older than v0.9.4?

**Comment by sogriffin98** [comment]
I have just checked the version and it is v0.9.4

**Comment by nicolasguillemin** [comment]
Hello
I had the same issue on my system, seems to be related with a switch to python 3.10. It is related with bokeh package.
I solved it after installing holoviews by running "pip install holoviews" (I used as sudo for system wide).
It installed a dependancy for bokeh, could be the one needed for nanoQC at the end.
Hope it helped !

**Comment by givdieri** [comment]
> Hello I had the same issue on my system, seems to be related with a switch to python 3.10. It is related with bokeh package. I solved it after installing holoviews by running "pip install holoviews" (I used as sudo for system wide). It installed a dependancy for bokeh, could be the one needed for nanoQC at the end. Hope it helped !

This fixed the issue for me as well!

**Comment by sogriffin98** [comment]
> Hello I had the same issue on my system, seems to be related with a switch to python 3.10. It is related with bokeh package. I solved it after installing holoviews by running "pip install holoviews" (I used as sudo for system wide). It installed a dependancy for bokeh, could be the one needed for nanoQC at the end. Hope it helped !

Thank you! It worked

**Comment by marceelrf** [comment]
Hello, I'm facing the same problem. I tried @nicolasguillemin  solution and it didn't work. 

My python version is 3.11, but I also tried using a virtual environment with version 3.10.

Do you have any idea what this error might be?

Please let me know if you need any more information.

**Comment by evayfang2019** [comment]
I met the same issue. I changed the Python version (3.8/3.9/3.10) and installed holoviews by running "pip install holoviews", and all failed.
