### ISSUE TITLE
no axis labels on histogram

### ISSUE THREAD

**Issue by chucknordy** [wdecoster/nanoQC#18]
Hi -- I recently was pointed to your NanoPack suite of tools and am enjoying checking out all the functionality you have made available -- thanks so much for this package!

For nanoQC, I'm guessing that the first plot (the histogram) is meant to show the read length distribution?  However, there are no labels on the axes, so I'm not certain.

A tiny suggestion, for the nucleotide frequency plots, it might be nice to add say a horizontal dashed line at f=0.25, just as a visual guide to the null case of 25% frequency of each type.  (This might be especially helpful when the two plots, for the first and last 100 bases, have different vertical ranges.)

Also it doesn't seem to affect functionality, but I thought I would mention (similar to #13 ) that there is a (new?) Bokeh warning:
`BokehDeprecationWarning: plot_width and plot_height was deprecated in Bokeh 2.4.0 and will be removed, use width or height instead.
`

**Comment by wdecoster** [comment]
Thank you for your patience. Please try v0.10.0, which should have some fixes!
