### ISSUE TITLE
nanoPlot and nanoQC TypeError

### ISSUE THREAD

**Issue by DaniPaulo** [wdecoster/nanoQC#20]
I'm trying to use nanoPlot and/or nanoQC but getting the following error (both using pip and conda for installation). 
Can you help me?

```
Traceback (most recent call last):
  File "/home/daniel.paulo/.local/lib/python3.9/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper
```

**Comment by wdecoster** [comment]
Which command are you trying? Could it be that your Biopython version is outdated?

**Comment by DaniPaulo** [comment]
Hi, thank you for the response. It turned out that I had some corrupted fastq.gz files. All it's good now. Thank you again, - Dani.

**Comment by wdecoster** [comment]
Thanks for the feedback!
