### ISSUE TITLE
Seeking Assistance with nanoQC Tool Error

### ISSUE THREAD

**Issue by Mitya-T** [wdecoster/nanoQC#21]
Hello,

I am currently encountering an issue with the nanoQC tool. After installing it via `pip install`, I attempted to run a simple QC run on my `fastq.gz `file using the command: 

`nanoQC -o . barcode03.fastq.gz`

However, I received an error message after approximately 15 seconds of work:

`Traceback (most recent call last):  File "/opt/conda/bin/nanoQC", line 8, in <module>    sys.exit(main())  File "/opt/conda/lib/python3.10/site-packages/nanoQC/nanoQC.py", line 43, in main    save(gridplot(children=[[hist], seq_plots, qual_plots],TypeError: gridplot() got an unexpected keyword argument 'plot_width'`

I would appreciate any suggestions or solutions to resolve this issue. Thank you in advance for your assistance.

Best Regards.

**Comment by dnaase** [comment]
i met the same problem.

**Comment by Mars-fi** [comment]
I also met this problem. Is there any solution?

**Comment by wdecoster** [comment]
Thank you for your patience. This should be solved in v0.10.0!
