### ISSUE TITLE
`--outdir` not specifying location of html

### ISSUE THREAD

**Issue by nick-youngblut** [wdecoster/nanoQC#5]
I'm running `nanoqc v0.7.0` with the following:

```
nanoQC --outdir test_output ecoli.fastq.gz
```

...and only the `*.log` file is written to the designated output directory, while the `*html` output file is written to the current working directory.

**Comment by wdecoster** [comment]
Oh yes, that's an oversight. I'll fix this in a couple of days since I'm on holiday.

**Comment by wdecoster** [comment]
This should be fixed in nanoQC v0.7.1, now available on PyPI/pip. Please keep in mind that nanoQC is less mature than my other tools, I welcome suggestions and contributions.
