### ISSUE TITLE
Installation issues with nanoqc/nanopack

### ISSUE THREAD

**Issue by aruginkgo** [wdecoster/nanoQC#8]
When trying to install nanopack using Python3 and `setup.py`, I get the error:

```
Installed /home/aru/.local/lib/python3.6/site-packages/nanopack-1.0.0-py3.6.egg
Processing dependencies for nanopack==1.0.0
Searching for nanoQC>=0.5.0
Reading https://pypi.python.org/simple/nanoQC/
Downloading https://files.pythonhosted.org/packages/b8/19/f4b22ff19dff896ace5bf06bbc69e5dc1ba895dfa28ed04cc68e72d0bb4a/nanoQC-0.8.0.tar.gz#sha256=e49e9a432da5e0a0fa113b7efdb522450eb7001cfcc14bc703d7bc631cf3edbc
Best match: nanoQC 0.8.0
Processing nanoQC-0.8.0.tar.gz
Writing /tmp/easy_install-wss4i6et/nanoQC-0.8.0/setup.cfg
Running nanoQC-0.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wss4i6et/nanoQC-0.8.0/egg-dist-tmp-daxatsa9
error: [Errno 2] No such file or directory: '/tmp/easy_install-wss4i6et/nanoQC-0.8.0/README.md'
```

I resolved this by pip3 installing nanoQC==0.5.0, so something might be awry with v0.8.0

There were other installation errors with Nanopack, but I am not sure if they are related to nanoQC; I can make another issue on the Nanopack repo if you want.

**Comment by wdecoster** [comment]
Thanks for reporting this, I'll fix it (probably later today).

**Comment by wdecoster** [comment]
I have pushed nanoQC v0.8.1 to PyPI in which this issue should be solved. Can you confirm?

I have also adapted the version numbers in NanoPack - so please let me know if you see installation errors there.
